name: Crear versión y subir artefactos
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v2

      - name: Crear carpeta de versión
        run: mkdir -p versioned-folder

      - name: Generar contenido de versión
        run: echo "Contenido de la versión" > versioned-folder/version.txt

      - name: Subir artefactos
        uses: actions/upload-artifact@v3
        with:
          name: versioned-artifacts
          path: versioned-folder
