name: Post api

on: workflow_dispatch

jobs:
  deployment:

    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://127.0.0.1:8081/prueba/saludo'
        method: 'POST'
        data: '{"mensaje":"Hola desde github"}'
