name: Make POST Request

on: [workflow_dispatch]

jobs:
  make-post-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          echo "Installing dependencies..."
          yarn install
      - run: |
          echo "Making a POST request to the API..."
          response=$(curl -X POST -H "Content-Type: application/json" -d '{"name": "Bard"}' https://api.github.com/users)
          echo $(curl -X POST -H "Content-Type: application/json" -d '{"name": "Bard"}' https://api.github.com/users)
      - run: |
          echo "Parsing the JSON response..."
          data=$(echo "$response" | jq -r .)
      - run: |
          echo "Printing the JSON response..."
          echo "$data"
