# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Post api

on: workflow_dispatch

jobs:
  post:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install curl
      run: sudo apt-get install curl
      
    - name: Perform HTTP Post
      run: curl -X POST http://localhost:8081/prueba -d '{"mensaje":"Hola desde github"}'
