name: Request Jira
on: 
 push:
  branches:
  - pruebaExitCode

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Sending request failed
        run: | 
            yes | sudo apt-get install jq

            response=$(curl --request POST \
            --url 'https://alrodri.atlassian.net/rest/api/3/issue/AD-2/comment' \
            --user '${{secrets.USER_JIRA}}d:${{secrets.TOKEN_JIRA}}' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{
            "body": {
                "content": [
                {
                    "content": [
                    {
                        "text": "Comment",
                        "type": "text"
                    }
                    ],
                    "type": "paragraph"
                }
                ],
                "type": "doc",
                "version": 1
            }
            }')
            echo "$response"

            if grep -q '"errorMessages":' <<< "$response"; then
                error_messages=$(echo "$response" | jq -r '.errorMessages[]')
                echo "$error_messages"
                exit 1
            else
                echo "Ejecución exitosa"
                exit 0
            fi
                    